manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      - name: infused-kim
      url-base: https://github.com/infused-kim
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

      # zmk module for PS/2 mouse / TP driver
    - name: kb_zmk_ps2_mouse_trackpoint_driver
     remote: infused-kim
     revision: main
  self:
    path: config
